### PR TITLE
HM-15-and-HM-20 added Services and tests for them.

### PR DESCRIPTION
**Pull request by Petkov06**

### CODE REVIEW

**Review by ivomihailov06 — COMMENTED** [review]
sehr gut but i cant finde every test!!!!!!

**Review by ivomihailov06 — COMMENTED** [review]
top

**Review by ectky — COMMENTED** [review]
Code coverage screenshot?

**Comment by ivomihailov06** [comment]
> Code coverage screenshot?

image

**Comment by Petkov06** [comment]
> Code coverage screenshot?

image

**Review by ivomihailov06 — COMMENTED** [review]
Dobre

**Review by ectky — APPROVED** [review]

**Pull request merged**
